// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: auth.go
package auth

import (
    "time"
)

 
func (t *Token) GetExpiredAt() *time.Time {
    if t == nil {
        return nil
    }
	return t.ExpiredAt
}
 
func (a *AuthSudir) GetUser() (_User *UserSudir) {
    if a == nil {
        return nil
    }
	return a.User
}
 
func (a *AuthPortalParams) GetDevice() (_Device *Device) {
    if a == nil {
        return nil
    }
	return a.Device
}



