// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: device.go
package auth

 
func (d *Device) GetSudirInfo() (_SudirInfo *SudirInfo) {
    if d == nil {
        return nil
    }
	return d.SudirInfo
}



