// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: session.go
package auth

import (
    "time"
)

 
func (s *Session) GetID() (_ID *SessionID) {
    if s == nil {
        return nil
    }
	return s.ID
}
 
func (s *Session) GetUser() (_User *User) {
    if s == nil {
        return nil
    }
	return s.User
}
 
func (s *Session) GetDevice() (_Device *Device) {
    if s == nil {
        return nil
    }
	return s.Device
}
 
func (s *Session) GetActivePortal() (_ActivePortal *ActivePortal) {
    if s == nil {
        return nil
    }
	return s.ActivePortal
}
 
func (s *Session) GetLastActiveTime() *time.Time {
    if s == nil {
        return nil
    }
	return s.LastActiveTime
}



