// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: user.go
package auth

 
func (u *User) GetEmployee() (_Employee *Employee) {
    if u == nil {
        return nil
    }
	return u.Employee
}
 
func (u *User) GetPerson() (_Person *Person) {
    if u == nil {
        return nil
    }
	return u.Person
}



