// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: types.go
package entity

import (
    "time"
)

 
func (p *Pagination) GetLastCreatedTime() *time.Time {
    if p == nil {
        return nil
    }
	return p.LastCreatedTime
}
 
func (p *Pagination) GetLimit() *int {
    if p == nil {
        return nil
    }
	return p.Limit
}
 
func (p *Pagination) GetTotal() *int {
    if p == nil {
        return nil
    }
	return p.Total
}
 
func (s *StringPagination) GetLastCreatedTime() *time.Time {
    if s == nil {
        return nil
    }
	return s.LastCreatedTime
}
 
func (s *StringPagination) GetLimit() *int {
    if s == nil {
        return nil
    }
	return s.Limit
}
 
func (s *StringPagination) GetTotal() *int {
    if s == nil {
        return nil
    }
	return s.Total
}



