// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: feature.go
package portal

import (
    "time"
)

 
func (f *Feature) GetCreatedAt() *time.Time {
    if f == nil {
        return nil
    }
	return f.CreatedAt
}
 
func (f *Feature) GetUpdatedAt() *time.Time {
    if f == nil {
        return nil
    }
	return f.UpdatedAt
}



