// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: image.go
package portal

import (
    "time"
)

 
func (i *Image) GetCreatedAt() *time.Time {
    if i == nil {
        return nil
    }
	return i.CreatedAt
}
 
func (i *Image) GetUpdatedAt() *time.Time {
    if i == nil {
        return nil
    }
	return i.UpdatedAt
}



