// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: organization.go
package portal

import (
    "time"
    "git.mos.ru/buch-cloud/moscow-team-2.0/backend/web-api.git/internal/entity"
)

 
func (o *Organization) GetLiquidatedAt() *string {
    if o == nil {
        return nil
    }
	return o.LiquidatedAt
}
 
func (o *Organization) GetCreatedAt() *time.Time {
    if o == nil {
        return nil
    }
	return o.CreatedAt
}
 
func (o *Organization) GetUpdatedAt() *time.Time {
    if o == nil {
        return nil
    }
	return o.UpdatedAt
}
 
func (o *OrganizationGrbs) GetStartDate() *string {
    if o == nil {
        return nil
    }
	return o.StartDate
}
 
func (o *OrganizationsWithPagination) GetPagination() (_Pagination *entity.StringPagination) {
    if o == nil {
        return nil
    }
	return o.Pagination
}



