// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: portal.go
package portal

import (
    "time"
)

 
func (p *Portal) GetCreatedAt() *time.Time {
    if p == nil {
        return nil
    }
	return p.CreatedAt
}
 
func (p *Portal) GetUpdatedAt() *time.Time {
    if p == nil {
        return nil
    }
	return p.UpdatedAt
}
 
func (p *Portal) GetDeletedAt() *time.Time {
    if p == nil {
        return nil
    }
	return p.DeletedAt
}



