// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: question.go
package portal

import (
    "time"
)

 
func (q *Question) GetCreatedAt() *time.Time {
    if q == nil {
        return nil
    }
	return q.CreatedAt
}
 
func (q *Question) GetUpdatedAt() *time.Time {
    if q == nil {
        return nil
    }
	return q.UpdatedAt
}
 
func (q *Question) GetDeletedAt() *time.Time {
    if q == nil {
        return nil
    }
	return q.DeletedAt
}



