version: "3.4"

services:
    proxy:
        container_name: auth_proxy
        build:
            context: ./nginx
            args:
                HOST_URL: ${HOST_URL}
        restart: always
        environment:
            APP_HOST: ${DEV_HOST}
            APP_PORT: ${HTTP_PORT}

    redis:
        container_name: auth_redis
        build:
            context: ./redis
        environment:
            - TZ=Europe/Moscow
        volumes:
            -   ./redis/data:/data
        entrypoint:
            redis-server --appendonly yes --maxmemory 512M
        restart: always


networks:
    host:
        driver: host
        external: true