// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: answer.go
package entitySurveys

import (
    "time"
    "github.com/google/uuid"
)

 
func (a *AnswerRules) GetContentMinLength() *int {
    if a == nil {
        return nil
    }
	return a.ContentMinLength
}
 
func (a *AnswerRules) GetContentMaxLength() *int {
    if a == nil {
        return nil
    }
	return a.ContentMaxLength
}
 
func (a *AnswerRules) GetContentMinDigit() *int {
    if a == nil {
        return nil
    }
	return a.ContentMinDigit
}
 
func (a *AnswerRules) GetContentMaxDigit() *int {
    if a == nil {
        return nil
    }
	return a.ContentMaxDigit
}
 
func (a *AnswerVariant) GetID() (_ID *AnswerID) {
    if a == nil {
        return nil
    }
	return a.ID
}
 
func (a *AnswerVariant) GetQuestionID() (_QuestionID *QuestionID) {
    if a == nil {
        return nil
    }
	return a.QuestionID
}
 
func (a *AnswerVariant) GetImage() (_Image *Image) {
    if a == nil {
        return nil
    }
	return a.Image
}
 
func (a *AnswerVariant) GetRules() (_Rules *AnswerRules) {
    if a == nil {
        return nil
    }
	return a.Rules
}
 
func (a *AnswerVariant) GetDeletedAt() *time.Time {
    if a == nil {
        return nil
    }
	return a.DeletedAt
}
 
func (r *RespondentAnswer) GetID() *uuid.UUID {
    if r == nil {
        return nil
    }
	return r.ID
}
 
func (r *RespondentAnswer) GetQuestionID() (_QuestionID *QuestionID) {
    if r == nil {
        return nil
    }
	return r.QuestionID
}
 
func (r *RespondentAnswer) GetRespondentId() (_RespondentId *RespondentID) {
    if r == nil {
        return nil
    }
	return r.RespondentId
}



