// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: image.go
package entitySurveys

 
func (i *Image) GetExternalImageInfo() (_ExternalImageInfo *ExternalProperties) {
    if i == nil {
        return nil
    }
	return i.ExternalImageInfo
}



