// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: question.go
package entitySurveys

import (
    "time"
)

 
func (q *QuestionRules) GetPickMinCount() *int {
    if q == nil {
        return nil
    }
	return q.PickMinCount
}
 
func (q *QuestionRules) GetPickMaxCount() *int {
    if q == nil {
        return nil
    }
	return q.PickMaxCount
}
 
func (q *Question) GetID() (_ID *QuestionID) {
    if q == nil {
        return nil
    }
	return q.ID
}
 
func (q *Question) GetSurveyID() (_SurveyID *SurveyID) {
    if q == nil {
        return nil
    }
	return q.SurveyID
}
 
func (q *Question) GetRules() (_Rules *QuestionRules) {
    if q == nil {
        return nil
    }
	return q.Rules
}
 
func (q *Question) GetDeletedAt() *time.Time {
    if q == nil {
        return nil
    }
	return q.DeletedAt
}



