// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: survey.go
package entitySurveys

import (
    "time"
)

 
func (s *Survey) GetID() (_ID *SurveyID) {
    if s == nil {
        return nil
    }
	return s.ID
}
 
func (s *Survey) GetCreatedAt() *time.Time {
    if s == nil {
        return nil
    }
	return s.CreatedAt
}
 
func (s *Survey) GetUpdatedAt() *time.Time {
    if s == nil {
        return nil
    }
	return s.UpdatedAt
}
 
func (s *Survey) GetDeletedAt() *time.Time {
    if s == nil {
        return nil
    }
	return s.DeletedAt
}
 
func (s *Survey) GetRespondent() (_Respondent *SurveyRespondent) {
    if s == nil {
        return nil
    }
	return s.Respondent
}
 
func (p *Pagination) GetLastId() (_LastId *SurveyID) {
    if p == nil {
        return nil
    }
	return p.LastId
}
 
func (p *Pagination) GetLastDate() *time.Time {
    if p == nil {
        return nil
    }
	return p.LastDate
}



