// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: absence.go
package employees_search

import (
    timeUtils "git.mos.ru/buch-cloud/moscow-team-2.0/build/time-utils.git"
)

 
 
func (a *Absence) GetStartDatePtr() *timeUtils.Date {
    if a == nil {
        return nil
    }
	return a.StartDate
}
 
func (a *Absence) GetEndDatePtr() *timeUtils.Date {
    if a == nil {
        return nil
    }
	return a.EndDate
}



 
func (a *Absence) GetName() string {
    if a == nil {
        return ""
    }
	return a.Name
}
 
func (a *Absence) GetStartDate() (_StartDate timeUtils.Date) {
    if a == nil || a.StartDate == nil  {
        return 
    }
	return *a.StartDate
}
 
func (a *Absence) GetEndDate() (_EndDate timeUtils.Date) {
    if a == nil || a.EndDate == nil  {
        return 
    }
	return *a.EndDate
}



