// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: employee.go
package employees_search

 
func (e *Employee) GetMiddleName() *string {
    if e == nil {
        return nil
    }
	return e.MiddleName
}
 
func (e *Employee) GetPosition() (_Position *Position) {
    if e == nil {
        return nil
    }
	return e.Position
}
 
func (e *Employee) GetOIV() (_OIV *OIV) {
    if e == nil {
        return nil
    }
	return e.OIV
}
 
func (e *Employee) GetProduct() (_Product *Product) {
    if e == nil {
        return nil
    }
	return e.Product
}
 
func (e *Employee) GetOrganization() (_Organization *Organization) {
    if e == nil {
        return nil
    }
	return e.Organization
}
 
func (e *Employee) GetStructure() (_Structure *Structure) {
    if e == nil {
        return nil
    }
	return e.Structure
}
 
func (e *Employee) GetStatuses() (_Statuses *Statuses) {
    if e == nil {
        return nil
    }
	return e.Statuses
}
 
func (s *Structure) GetPosition() (_Position *Position) {
    if s == nil {
        return nil
    }
	return s.Position
}
 
func (s *Structure) GetSubdivision() (_Subdivision *Subdivision) {
    if s == nil {
        return nil
    }
	return s.Subdivision
}
 
func (s *Structure) GetOrganization() (_Organization *Organization) {
    if s == nil {
        return nil
    }
	return s.Organization
}
 
func (s *Structure) GetOIV() (_OIV *OIV) {
    if s == nil {
        return nil
    }
	return s.OIV
}



