// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: filter.go
package employees_search

 
func (f *FiltersRequest) GetFilters() (_Filters *Filters) {
    if f == nil {
        return nil
    }
	return f.Filters
}
 
func (f *FiltersRequest) GetOptions() (_Options *Options) {
    if f == nil {
        return nil
    }
	return f.Options
}



