// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: params.go
package employees_search

 
func (s *SearchParams) GetFilters() (_Filters *FiltersParams) {
    if s == nil {
        return nil
    }
	return s.Filters
}
 
func (s *SearchParams) GetOptions() (_Options *OptionsParams) {
    if s == nil {
        return nil
    }
	return s.Options
}
 
func (s *SearchParams) GetAfterID() *string {
    if s == nil {
        return nil
    }
	return s.AfterID
}
 
func (o *OptionsParams) GetWithFired() (_WithFired *FiredDateRange) {
    if o == nil {
        return nil
    }
	return o.WithFired
}



