// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: search.go
package employees_search

import (
    timeUtils "git.mos.ru/buch-cloud/moscow-team-2.0/build/time-utils.git"
)

 
func (s *SearchRequest) GetFilters() (_Filters *Filters) {
    if s == nil {
        return nil
    }
	return s.Filters
}
 
func (s *SearchRequest) GetOptions() (_Options *Options) {
    if s == nil {
        return nil
    }
	return s.Options
}
 
func (s *SearchRequest) GetAfterID() *string {
    if s == nil {
        return nil
    }
	return s.AfterID
}
 
func (f *Filters) GetBirthDay() *string {
    if f == nil {
        return nil
    }
	return f.BirthDay
}
 
func (s *SearchAbsence) GetFrom() (_From *timeUtils.Date) {
    if s == nil {
        return nil
    }
	return s.From
}
 
func (s *SearchAbsence) GetTo() (_To *timeUtils.Date) {
    if s == nil {
        return nil
    }
	return s.To
}
 
func (o *Options) GetWithFired() (_WithFired *FiredDateRange) {
    if o == nil {
        return nil
    }
	return o.WithFired
}
 
func (f *FiredDateRange) GetFrom() (_From *timeUtils.Date) {
    if f == nil {
        return nil
    }
	return f.From
}
 
func (f *FiredDateRange) GetTo() (_To *timeUtils.Date) {
    if f == nil {
        return nil
    }
	return f.To
}
 
func (p *Params) GetFrom() (_From *timeUtils.Date) {
    if p == nil {
        return nil
    }
	return p.From
}
 
func (p *Params) GetTo() (_To *timeUtils.Date) {
    if p == nil {
        return nil
    }
	return p.To
}



