// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: banners.go
package entityBanners

import (
    "time"
)

 
func (b *BannerInfo) GetID() string {
    if b == nil {
        return ""
    }
	return b.ID
}
 
func (b *BannerInfo) GetType() (_Type BannerType) {
    if b == nil {
        return 
    }
	return b.Type
}
 
func (b *BannerInfo) GetPosition() *int {
    if b == nil {
        return nil
    }
	return b.Position
}
 
func (b *Banner) GetID() string {
    if b == nil {
        return ""
    }
	return b.ID
}
 
func (b *Banner) GetBannerType() (_BannerType BannerType) {
    if b == nil {
        return 
    }
	return b.BannerType
}
 
func (b *Banner) GetCreatedAt() time.Time {
    if b == nil {
        return time.Time{}
    }
	return b.CreatedAt
}
 
func (b *Banner) GetUpdatedAt() *time.Time {
    if b == nil {
        return nil
    }
	return b.UpdatedAt
}
 
func (b *Banner) GetContent() Content {
    if b == nil {
        return Content{}
    }
	return b.Content
}
 
func (c *Content) GetPosition() *int {
    if c == nil {
        return nil
    }
	return c.Position
}
 
func (c *Content) GetDesktopImageID() string {
    if c == nil {
        return ""
    }
	return c.DesktopImageID
}
 
func (c *Content) GetMobileImageID() *string {
    if c == nil {
        return nil
    }
	return c.MobileImageID
}
 
func (c *Content) GetUrl() string {
    if c == nil {
        return ""
    }
	return c.Url
}



