namespace: service-develop

app:
    name: auth
    image: git.mos.ru:5050/buch-cloud/mosteam/golang/aispu/auth
    tag: latest-develop
    replicas: 3

resources:
    limits:
        cpu: "200m"
        memory: "1Gi"
    requests:
        cpu: "100m"
        memory: "500Mi"

annotations:
    prometheus.io/scrape: true
    prometheus.io/path: /metrics
    prometheus.io/port: 8080

env_data:
    - name: LOG_LEVEL
      value: debug
    - name: APP_NAME
      value: auth
    - name: ENVIRONMENT
      value: develop
    - name: DEV_MODE
      value: true
    - name: SERVICE_HOST
      value: :8080
    - name: GRPC_HOST
      value: 0.0.0.0
    - name: GRPC_PORT
      value: 9999
    - name: EMPLOYEES_ENDPOINT
      value: employees-service-develop:9999

service:
    name: auth
    type: ClusterIP
    ports:
        - name: service
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: grpc
          port: 9999
          protocol: TCP
          targetPort: 9999

http_ingress:
    enabled: true
    name: http-ingress-auth-develop
    hostname: internal-komanda.mos.local
    rules:
        - path: /develop/service/auth
          port: 8080

grpc_ingress:
    enabled: true
    name: grpc-ingress-auth-develop
    hostname: internal-komanda.mos.local
    rules:
        - path: /develop/grpc/auth
          port: 9999