namespace: service-develop

app:
  name: web-api
  image: git.mos.ru:5050/buch-cloud/mosteam/golang/aispu/web-api
  tag: latest-develop
  replicas: 3

resources:
    limits:
        cpu: "2000m"
        memory: "4Gi"
    requests:
        cpu: "900m"
        memory: "1Gi"

annotations:
    prometheus.io/scrape: true
    prometheus.io/path: /metrics
    prometheus.io/port: 8080

env_data:
  - name: LOG_LEVEL
    value: debug
  - name: APP_NAME
    value: web-api
  - name: ENVIRONMENT
    value: develop
  - name: DEV_MODE
    value: true
  - name: SERVICE_HOST
    value: :8080
  - name: HTTP_HOST
    value: 0.0.0.0
  - name: HTTP_PORT
    value: 80
  - name: HTTP_EXTERNAL_HOST
    value: develop-komanda.mos.ru
  - name: HTTP_SCHEMA
    value: https
  - name: WEB_AUTH_REDIRECT_URI
    value: /redirect
  - name: PORTALS_ENDPOINT
    value: portals-service-develop:9999
  - name: PORTALSV2_ENDPOINT
    value: portals-v2-service-develop:9999
  - name: SURVEYS_ENDPOINT
    value: surveys-service-develop:9999
  - name: AUTH_FACADE_ENDPOINT
    value: auth-facade-service-develop:9999
  - name: PROXY_FACADE_ENDPOINT
    value: proxy-facade-service-develop:9999
  - name: EMPLOYEES_SEARCH_ENDPOINT
    value: employees-search-service-develop:9999
  - name: FILES_ENDPOINT
    value: file-service-service-develop:9999
  - name: EMPLOYEES_ENDPOINT
    value: employees-service-develop:9999
  - name: ANALYTICS_ENDPOINT
    value: analytics-service-develop:9999
  - name: PORTALS_FACADE_ENDPOINT
    value: portals-facade-service-develop:9999
  - name: NEWS_ENDPOINT
    value: news-service-develop:9999
  - name: NEWS_FACADE_ENDPOINT
    value: news-facade-service-develop:9999
  - name: BANNERS_ENDPOINT
    value: banners-service-develop:9999

service:
  name: web-api
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: service
      port: 8080
      protocol: TCP
      targetPort: 8080

ingress:
  enabled: true
  name: ingress-web-api-develop
  hostname: develop-komanda.mos.ru
  rules:
    - path: /web
      port: 80
    - path: /web
      port: 8080
