namespace: services

app:
    name: auth
    image: git.mos.ru:5050/buch-cloud/mosteam/golang/aispu/auth
    tag: latest
    replicas: 5

resources:
    limits:
        cpu: "2"
        memory: "4Gi"
    requests:
        cpu: "2"
        memory: "4Gi"

annotations:
    prometheus.io/scrape: true
    prometheus.io/path: /metrics
    prometheus.io/port: 8080

env_data:
    - name: LOG_LEVEL
      value: warn
    - name: APP_NAME
      value: auth
    - name: ENVIRONMENT
      value: prod
    - name: DEV_MODE
      value: false
    - name: SERVICE_HOST
      value: :8080
    - name: GRPC_HOST
      value: 0.0.0.0
    - name: GRPC_PORT
      value: 9999
    - name: EMPLOYEES_ENDPOINT
      value: employees-services:9999

service:
    name: auth
    type: ClusterIP
    ports:
        - name: service
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: grpc
          port: 9999
          protocol: TCP
          targetPort: 9999

http_ingress:
    enabled: true
    name: http-ingress-auth-production
    hostname: internal-komanda.mos.local
    rules:
        - path: /production/service/auth
          port: 8080

grpc_ingress:
    enabled: true
    name: grpc-ingress-auth-production
    hostname: internal-komanda.mos.local
    rules:
        - path: /production/grpc/auth
          port: 9999