// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: comments.go
package news

import (
	entityNews "git.mos.ru/buch-cloud/moscow-team-2.0/backend/web-api.git/internal/entity/news"
	"github.com/google/uuid"
)

func (n *NewComment) GetAuthorID() *uuid.UUID {
	if n == nil {
		return nil
	}
	return n.AuthorID
}

func (f *FilterComments) GetAfterID() *uuid.UUID {
	if f == nil {
		return nil
	}
	return f.AfterID
}

func (f *FilterComments) GetVisitor() (_Visitor *entityNews.Visitor) {
	if f == nil {
		return nil
	}
	return f.Visitor
}
