// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: banners.go
package dtoBanners

import (
    entityBanners "git.mos.ru/buch-cloud/moscow-team-2.0/backend/web-api.git/internal/entity/banners"
)

 
func (s *SetBanner) GetID() *string {
    if s == nil {
        return nil
    }
	return s.ID
}
 
func (s *SetBanner) GetType() (_Type entityBanners.BannerType) {
    if s == nil {
        return 
    }
	return s.Type
}
 
func (s *SetBanner) GetPosition() *int {
    if s == nil {
        return nil
    }
	return s.Position
}
 
func (s *SetBanner) GetDesktopImageID() string {
    if s == nil {
        return ""
    }
	return s.DesktopImageID
}
 
func (s *SetBanner) GetMobileImageID() *string {
    if s == nil {
        return nil
    }
	return s.MobileImageID
}
 
func (s *SetBanner) GetUrl() string {
    if s == nil {
        return ""
    }
	return s.Url
}



