# HTTP Ingress
{{- if .Values.http_ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Values.http_ingress.name }}
    annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
    ingressClassName: nginx
    rules:
        - host: {{ .Values.http_ingress.hostname }}
          http:
              paths:
                  {{- range .Values.http_ingress.rules }}
                  - backend:
                        service:
                            name: {{$.Values.service.name}}-{{ $.Values.namespace }}
                            port:
                                number: {{ .port }}
                    path: {{ .path }}(/|$)(.*)
                    pathType: ImplementationSpecific
                  {{- end }}
{{- end }}

# GRPC Ingress
{{- if .Values.grpc_ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Values.grpc_ingress.name }}
    annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
    ingressClassName: nginx
    rules:
        - host: {{ .Values.grpc_ingress.hostname }}
          http:
              paths:
              {{- range .Values.grpc_ingress.rules }}
              - backend:
                    service:
                        name: {{$.Values.service.name}}-{{ $.Values.namespace }}
                        port:
                            number: {{ .port }}
                path: {{ .path }}
                pathType: Prefix
              {{- end }}
{{- end }}
