// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: comments.go
package news

import (
	"time"
)

func (n *NewsComment) GetCreateAtPtr() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreateAt
}

func (n *NewsComment) GetCreateAt() time.Time {
	if n == nil || n.CreateAt == nil {
		return time.Time{}
	}
	return *n.CreateAt
}
