// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: news.go
package news

import (
    "time"
    "github.com/google/uuid"
)

 
func (n *NewNews) GetImageIDPtr() *uuid.UUID {
    if n == nil {
        return nil
    }
	return n.ImageID
}
 
func (n *NewNews) GetProviderOrganizationIDPtr() *uuid.UUID {
    if n == nil {
        return nil
    }
	return n.ProviderOrganizationID
}
 
func (n *NewNews) GetProviderProductIDPtr() *uuid.UUID {
    if n == nil {
        return nil
    }
	return n.ProviderProductID
}
 
func (n *NewNews) GetPublishDatePtr() *time.Time {
    if n == nil {
        return nil
    }
	return n.PublishDate
}
 
func (u *UpdateNews) GetImageIDPtr() *string {
    if u == nil {
        return nil
    }
	return u.ImageID
}
 
func (u *UpdateNews) GetCategoryIDPtr() *string {
    if u == nil {
        return nil
    }
	return u.CategoryID
}
 
func (u *UpdateNews) GetProviderOrganizationIdPtr() *string {
    if u == nil {
        return nil
    }
	return u.ProviderOrganizationId
}
 
func (u *UpdateNews) GetProviderProductIdPtr() *string {
    if u == nil {
        return nil
    }
	return u.ProviderProductId
}
 
func (u *UpdateNews) GetPublishDatePtr() *time.Time {
    if u == nil {
        return nil
    }
	return u.PublishDate
}
 
func (u *UpdateNews) GetUpdatedAtPtr() *time.Time {
    if u == nil {
        return nil
    }
	return u.UpdatedAt
}
 
func (n *News) GetImageIDPtr() *uuid.UUID {
    if n == nil {
        return nil
    }
	return n.ImageID
}
 
func (n *News) GetCategoryPtr() *NewsCategory {
    if n == nil {
        return nil
    }
	return n.Category
}
 
func (n *News) GetProviderOrganizationPtr() *NewsOrganization {
    if n == nil {
        return nil
    }
	return n.ProviderOrganization
}
 
func (n *News) GetProviderProductPtr() *NewsProduct {
    if n == nil {
        return nil
    }
	return n.ProviderProduct
}
 
func (n *News) GetUpdatedAtPtr() *time.Time {
    if n == nil {
        return nil
    }
	return n.UpdatedAt
}
 
func (n *News) GetCreateDatePtr() *time.Time {
    if n == nil {
        return nil
    }
	return n.CreateDate
}
 
func (n *News) GetPublishDatePtr() *time.Time {
    if n == nil {
        return nil
    }
	return n.PublishDate
}
 
func (s *SearchNewsResponseItem) GetImageIDPtr() *uuid.UUID {
    if s == nil {
        return nil
    }
	return s.ImageID
}
 
func (s *SearchNewsResponseItem) GetCategoryPtr() *NewsCategory {
    if s == nil {
        return nil
    }
	return s.Category
}
 
func (s *SearchNewsResponseItem) GetProviderOrganizationPtr() *NewsOrganization {
    if s == nil {
        return nil
    }
	return s.ProviderOrganization
}
 
func (s *SearchNewsResponseItem) GetProviderProductPtr() *NewsProduct {
    if s == nil {
        return nil
    }
	return s.ProviderProduct
}
 
func (s *SearchNewsResponseItem) GetCreateAtPtr() *time.Time {
    if s == nil {
        return nil
    }
	return s.CreateAt
}
 
func (s *SearchNewsResponseItem) GetPublishedAtPtr() *time.Time {
    if s == nil {
        return nil
    }
	return s.PublishedAt
}
 
func (a *Author) GetIDPtr() *uuid.UUID {
    if a == nil {
        return nil
    }
	return a.ID
}
 
func (a *Author) GetImageIDPtr() *uuid.UUID {
    if a == nil {
        return nil
    }
	return a.ImageID
}
 
func (n *NewsParticipants) GetIdPtr() *uuid.UUID {
    if n == nil {
        return nil
    }
	return n.Id
}
 
func (n *NewsParticipants) GetImageIDPtr() *uuid.UUID {
    if n == nil {
        return nil
    }
	return n.ImageID
}
 
func (u *UpdateNewsFlags) GetUpdatedAtPtr() *time.Time {
    if u == nil {
        return nil
    }
	return u.UpdatedAt
}



 
func (n *NewNews) GetImageID() uuid.UUID {
    if n == nil || n.ImageID == nil  {
        return uuid.Nil
    }
	return *n.ImageID
}
 
func (n *NewNews) GetProviderOrganizationID() uuid.UUID {
    if n == nil || n.ProviderOrganizationID == nil  {
        return uuid.Nil
    }
	return *n.ProviderOrganizationID
}
 
func (n *NewNews) GetProviderProductID() uuid.UUID {
    if n == nil || n.ProviderProductID == nil  {
        return uuid.Nil
    }
	return *n.ProviderProductID
}
 
func (n *NewNews) GetPublishDate() time.Time {
    if n == nil || n.PublishDate == nil  {
        return time.Time{}
    }
	return *n.PublishDate
}
 
func (u *UpdateNews) GetImageID() string {
    if u == nil || u.ImageID == nil  {
        return ""
    }
	return *u.ImageID
}
 
func (u *UpdateNews) GetCategoryID() string {
    if u == nil || u.CategoryID == nil  {
        return ""
    }
	return *u.CategoryID
}
 
func (u *UpdateNews) GetProviderOrganizationId() string {
    if u == nil || u.ProviderOrganizationId == nil  {
        return ""
    }
	return *u.ProviderOrganizationId
}
 
func (u *UpdateNews) GetProviderProductId() string {
    if u == nil || u.ProviderProductId == nil  {
        return ""
    }
	return *u.ProviderProductId
}
 
func (u *UpdateNews) GetPublishDate() time.Time {
    if u == nil || u.PublishDate == nil  {
        return time.Time{}
    }
	return *u.PublishDate
}
 
func (u *UpdateNews) GetUpdatedAt() time.Time {
    if u == nil || u.UpdatedAt == nil  {
        return time.Time{}
    }
	return *u.UpdatedAt
}
 
func (n *News) GetImageID() uuid.UUID {
    if n == nil || n.ImageID == nil  {
        return uuid.Nil
    }
	return *n.ImageID
}
 
func (n *News) GetCategory() (_Category NewsCategory) {
    if n == nil || n.Category == nil  {
        return 
    }
	return *n.Category
}
 
func (n *News) GetProviderOrganization() (_ProviderOrganization NewsOrganization) {
    if n == nil || n.ProviderOrganization == nil  {
        return 
    }
	return *n.ProviderOrganization
}
 
func (n *News) GetProviderProduct() (_ProviderProduct NewsProduct) {
    if n == nil || n.ProviderProduct == nil  {
        return 
    }
	return *n.ProviderProduct
}
 
func (n *News) GetUpdatedAt() time.Time {
    if n == nil || n.UpdatedAt == nil  {
        return time.Time{}
    }
	return *n.UpdatedAt
}
 
func (n *News) GetCreateDate() time.Time {
    if n == nil || n.CreateDate == nil  {
        return time.Time{}
    }
	return *n.CreateDate
}
 
func (n *News) GetPublishDate() time.Time {
    if n == nil || n.PublishDate == nil  {
        return time.Time{}
    }
	return *n.PublishDate
}
 
func (s *SearchNewsResponseItem) GetImageID() uuid.UUID {
    if s == nil || s.ImageID == nil  {
        return uuid.Nil
    }
	return *s.ImageID
}
 
func (s *SearchNewsResponseItem) GetCategory() (_Category NewsCategory) {
    if s == nil || s.Category == nil  {
        return 
    }
	return *s.Category
}
 
func (s *SearchNewsResponseItem) GetProviderOrganization() (_ProviderOrganization NewsOrganization) {
    if s == nil || s.ProviderOrganization == nil  {
        return 
    }
	return *s.ProviderOrganization
}
 
func (s *SearchNewsResponseItem) GetProviderProduct() (_ProviderProduct NewsProduct) {
    if s == nil || s.ProviderProduct == nil  {
        return 
    }
	return *s.ProviderProduct
}
 
func (s *SearchNewsResponseItem) GetCreateAt() time.Time {
    if s == nil || s.CreateAt == nil  {
        return time.Time{}
    }
	return *s.CreateAt
}
 
func (s *SearchNewsResponseItem) GetPublishedAt() time.Time {
    if s == nil || s.PublishedAt == nil  {
        return time.Time{}
    }
	return *s.PublishedAt
}
 
func (a *Author) GetID() uuid.UUID {
    if a == nil || a.ID == nil  {
        return uuid.Nil
    }
	return *a.ID
}
 
func (a *Author) GetImageID() uuid.UUID {
    if a == nil || a.ImageID == nil  {
        return uuid.Nil
    }
	return *a.ImageID
}
 
func (n *NewsParticipants) GetId() uuid.UUID {
    if n == nil || n.Id == nil  {
        return uuid.Nil
    }
	return *n.Id
}
 
func (n *NewsParticipants) GetImageID() uuid.UUID {
    if n == nil || n.ImageID == nil  {
        return uuid.Nil
    }
	return *n.ImageID
}
 
func (u *UpdateNewsFlags) GetUpdatedAt() time.Time {
    if u == nil || u.UpdatedAt == nil  {
        return time.Time{}
    }
	return *u.UpdatedAt
}



