// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: shared.go
package news

import (
    "github.com/google/uuid"
)

 
func (v *Visitor) GetEmployeeIDPtr() *uuid.UUID {
    if v == nil {
        return nil
    }
	return v.EmployeeID
}
 



 
func (v *Visitor) GetEmployeeID() uuid.UUID {
    if v == nil || v.EmployeeID == nil  {
        return uuid.Nil
    }
	return *v.EmployeeID
}
 
func (v *Visitor) GetPortalID() int {
    if v == nil {
        return 0
    }
	return v.PortalID
}



