// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: absences.go
package employee

import (
    timeUtils "git.mos.ru/buch-cloud/moscow-team-2.0/build/time-utils.git"
)

 
func (a *Absence) GetFrom() (_From *timeUtils.Date) {
    if a == nil {
        return nil
    }
	return a.From
}
 
func (a *Absence) GetTo() (_To *timeUtils.Date) {
    if a == nil {
        return nil
    }
	return a.To
}



