// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: employee.go
package employee

import (
    "time"
    timeUtils "git.mos.ru/buch-cloud/moscow-team-2.0/build/time-utils.git"
)

 
func (e *Employee) GetPhones() (_Phones *Phones) {
    if e == nil {
        return nil
    }
	return e.Phones
}
 
func (e *Employee) GetMainProduct() (_MainProduct *Product) {
    if e == nil {
        return nil
    }
	return e.MainProduct
}
 
func (e *Employee) GetStaffPosition() (_StaffPosition *StaffPosition) {
    if e == nil {
        return nil
    }
	return e.StaffPosition
}
 
func (e *Employee) GetSubdivisionTree() (_SubdivisionTree *SubdivisionTree) {
    if e == nil {
        return nil
    }
	return e.SubdivisionTree
}
 
func (e *Employee) GetManagementTree() (_ManagementTree *ManagementTree) {
    if e == nil {
        return nil
    }
	return e.ManagementTree
}
 
func (e *Employee) GetHeadManagement() (_HeadManagement *HeadManagement) {
    if e == nil {
        return nil
    }
	return e.HeadManagement
}
 
func (e *Employee) GetHeadStaffPosition() (_HeadStaffPosition *HeadStaffPosition) {
    if e == nil {
        return nil
    }
	return e.HeadStaffPosition
}
 
func (e *Employee) GetAbsence() (_Absence *Absence) {
    if e == nil {
        return nil
    }
	return e.Absence
}
 
func (e *Employee) GetWorkplace() (_Workplace *Workplace) {
    if e == nil {
        return nil
    }
	return e.Workplace
}
 
func (e *Employee) GetDateOfEmployment() (_DateOfEmployment *timeUtils.Date) {
    if e == nil {
        return nil
    }
	return e.DateOfEmployment
}
 
func (e *Employee) GetCreateTime() *time.Time {
    if e == nil {
        return nil
    }
	return e.CreateTime
}
 
func (e *Employee) GetUpdateTime() *time.Time {
    if e == nil {
        return nil
    }
	return e.UpdateTime
}
 
func (p *Phones) GetWorkNumber() *string {
    if p == nil {
        return nil
    }
	return p.WorkNumber
}
 
func (p *Phones) GetExtensionNumber() *string {
    if p == nil {
        return nil
    }
	return p.ExtensionNumber
}
 
func (h *History) GetEventTime() *time.Time {
    if h == nil {
        return nil
    }
	return h.EventTime
}



