// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: person.go
package employee

import (
    "time"
)

 
func (p *Person) GetSocials() (_Socials *Socials) {
    if p == nil {
        return nil
    }
	return p.Socials
}
 
func (p *Person) GetCreatedAt() *time.Time {
    if p == nil {
        return nil
    }
	return p.CreatedAt
}
 
func (p *Person) GetUpdatedAt() *time.Time {
    if p == nil {
        return nil
    }
	return p.UpdatedAt
}
 
func (s *Socials) GetChatID() *string {
    if s == nil {
        return nil
    }
	return s.ChatID
}



