// Code generated by DIT Nil Getters Generator. !!! DO NOT EDIT !!!
// Source: organization.go
package portals

import (
    "time"
    "git.mos.ru/buch-cloud/moscow-team-2.0/backend/web-api.git/internal/api/http/view"
)

 
func (o *Organization) GetLiquidatedAt() *string {
    if o == nil {
        return nil
    }
	return o.LiquidatedAt
}
 
func (o *Organization) GetCreatedAt() *time.Time {
    if o == nil {
        return nil
    }
	return o.CreatedAt
}
 
func (o *Organization) GetUpdatedAt() *time.Time {
    if o == nil {
        return nil
    }
	return o.UpdatedAt
}
 
func (o *OrganizationGrbs) GetStartDate() *string {
    if o == nil {
        return nil
    }
	return o.StartDate
}
 
func (o *OrganizationsWithPagination) GetPagination() (_Pagination *view.StringPagination) {
    if o == nil {
        return nil
    }
	return o.Pagination
}
 
func (f *FilterOrganizations) GetPagination() (_Pagination *view.StringPagination) {
    if f == nil {
        return nil
    }
	return f.Pagination
}
 
func (f *FilterOrganizations) GetOptions() (_Options *OrganizationsFilterOptions) {
    if f == nil {
        return nil
    }
	return f.Options
}



